### DISCUSSION TITLE
Scheduling Docker Container Command Execution based on Time Constraints

### DISCUSSION THREAD

**Discussion by NorkzYT** [Tyrrrz/DiscordChatExporter#1038] [Q&A] [answered]
I have thoroughly reviewed the [WIKI](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/.docs/Scheduling-Linux.md) that provides a script for scheduling in Linux. However, I am currently seeking a method to achieve scheduling within a Docker environment.

Is there a recommended approach to schedule a Docker container in such a way that a specific command, such as exportguild, is only executed between 20:00 and 05:00, and remains inactive until those hours are reached again?

I attempted to utilize an entry point with a bash script, but unfortunately, the command was not recognized in that context.

I would greatly appreciate any guidance or suggestions you can provide regarding this matter.

Thank you in advance for your assistance.

Current `docker-compose.yml` file contents:
```yml
version: '3.9'
services:

  discordchatexporter:
    image: tyrrrz/discordchatexporter:stable
    container_name: discordchatexporter
    restart: unless-stopped
    volumes:
      - /mnt/appdata/discord/chat-exporter:/out
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_TOKEN_BOT: true
    command: exportguild -g DISCORD_SERVER_ID --dateformat "dd/MM/yyyy HH:mm"
    networks:
      - proxy
    
networks:
  proxy:
    driver: bridge
    external: true
```
